openapi: 3.0.0
info:
  description: This is a sample API for a web store.
  version: 1.0.0
  title: Sample Store
paths:
  /:
    get:
      summary: Get all the available items
      description: ""
      operationId: getPet
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      summary: Add a new item to the store
      description: ""
      operationId: addPet
      requestBody:
        $ref: "#/components/requestBodies/Item"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"

  "/{itemId}":
    summary: Manipulates a specific item
    parameters:
      - name: itemId
        in: path
        description: ID of item that needs to be updated
        required: true
        schema:
          type: integer
          format: int64
    delete:
      summary: Deletes an item
      description: ""
      operationId: deleteItem
      parameters:
        - name: itemId
          in: path
          description: Item ID to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "404":
          description: Item not found
components:
  requestBodies:
    Item:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Item"
        application/xml:
          schema:
            $ref: "#/components/schemas/Item"
      description: Item object that needs to be added to the store
      required: true
  schemas:
    Item:
      type: object
      required:
        - name
        - description
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Item 12
        description:
          type: string
          example: This is item 12
