name: Node CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["16"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.ruby-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
